apiVersion: apps/v1
kind: Deployment
metadata:
  name: kvstore-leader
spec:
  selector:
    matchLabels:
      app: kvstore
  replicas: 1
  template:
    metadata:
      labels:
        app: kvstore
        r3: leader
    spec:
      containers:
        - name: r3-kvstore-leader
          image: r3muskteers/kvstore:latest
          ports:
            - containerPort: 11000
              protocol: TCP
            - containerPort: 12000
              protocol: TCP
            - containerPort: 13000
              protocol: TCP
          command: ["./kvstore"]
          #args: ["-logfolder=/tmp/"]
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kvstore-follower
spec:
  selector:
    matchLabels:
      app: kvstore
  replicas: 2
  template:
    metadata:
      labels:
        app: kvstore
        r3: follower
    spec:
      containers:
        - name: r3-kvstore
          image: r3muskteers/kvstore:latest
          ports:
            - containerPort: 11000
              protocol: TCP
            - containerPort: 12000
              protocol: TCP
            - containerPort: 13000
              protocol: TCP
          command: ["./kvstore"]
          #args: ["-logfolder=/tmp/"]
          env:
            # - name: MY_NODE_NAME
            #   valueFrom:
            #     fieldRef:
            #       fieldPath: spec.nodeName
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            # - name: MY_POD_SERVICE_ACCOUNT
            #   valueFrom:
            #     fieldRef:
            #       fieldPath: spec.serviceAccountName
---
apiVersion: v1
kind: Service
metadata:
  name: kvstore-svc
  labels:
    app: kvstore
spec:
  type: NodePort
  ports:
    - port: 11000
      targetPort: 11000
      protocol: TCP
      name: app-requests

    - port: 12000
      targetPort: 13000
      protocol: TCP
      name: raft

    - port: 13000
      targetPort: 13000
      protocol: TCP
      name: handle-joins

  selector:
    app: kvstore
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kvstore
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
